{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "085cf688-83b1-47ab-a7ac-fe982cc70df6",
   "metadata": {},
   "outputs": [],
   "source": [
    "import random"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "1f9894bb-a4d4-4c2f-9625-cd581d8362fc",
   "metadata": {},
   "outputs": [],
   "source": [
    "class MiniGamesHub:\n",
    "\n",
    "    def __init__(self):\n",
    "        self.player_score = 0\n",
    "        self.computer_score = 0\n",
    "\n",
    "    # ---------------------------------\n",
    "    # 1. Rock Paper Scissors\n",
    "    # ---------------------------------\n",
    "    def rock_paper_scissors(self):\n",
    "\n",
    "        print(\"\\n===== ROCK PAPER SCISSORS =====\")\n",
    "\n",
    "        choices = [\"rock\", \"paper\", \"scissors\"]\n",
    "\n",
    "        player = input(\"Enter rock, paper, or scissors: \").lower()\n",
    "\n",
    "        if player not in choices:\n",
    "            print(\"Invalid choice!\")\n",
    "            return\n",
    "\n",
    "        computer = random.choice(choices)\n",
    "\n",
    "        print(\"Computer chose:\", computer)\n",
    "\n",
    "        if player == computer:\n",
    "            print(\"It's a tie!\")\n",
    "\n",
    "        elif (\n",
    "            (player == \"rock\" and computer == \"scissors\")\n",
    "            or (player == \"paper\" and computer == \"rock\")\n",
    "            or (player == \"scissors\" and computer == \"paper\")\n",
    "        ):\n",
    "            print(\"You win!\")\n",
    "            self.player_score += 1\n",
    "\n",
    "        else:\n",
    "            print(\"Computer wins!\")\n",
    "            self.computer_score += 1\n",
    "\n",
    "        print(\"Player Score:\", self.player_score)\n",
    "        print(\"Computer Score:\", self.computer_score)\n",
    "\n",
    "\n",
    "    # ---------------------------------\n",
    "    # 2. Number Guessing Game\n",
    "    # ---------------------------------\n",
    "    def number_guessing(self):\n",
    "\n",
    "        print(\"\\n===== NUMBER GUESSING GAME =====\")\n",
    "\n",
    "        number = random.randint(1, 10)\n",
    "\n",
    "        attempts = 3\n",
    "\n",
    "        for attempt in range(1, attempts + 1):\n",
    "\n",
    "            try:\n",
    "                guess = int(input(\"Guess a number between 1 and 10: \"))\n",
    "\n",
    "                if guess == number:\n",
    "                    print(\"Congratulations! You guessed correctly!\")\n",
    "                    self.player_score += 1\n",
    "                    break\n",
    "\n",
    "                elif guess < number:\n",
    "                    print(\"Too low!\")\n",
    "\n",
    "                else:\n",
    "                    print(\"Too high!\")\n",
    "\n",
    "                print(\"Attempts remaining:\", attempts - attempt)\n",
    "\n",
    "            except ValueError:\n",
    "                print(\"Please enter a valid number.\")\n",
    "\n",
    "        else:\n",
    "            print(\"Game Over!\")\n",
    "            print(\"The correct number was:\", number)\n",
    "\n",
    "\n",
    "    # ---------------------------------\n",
    "    # 3. Dice Rolling Game\n",
    "    # ---------------------------------\n",
    "    def dice_rolling(self):\n",
    "\n",
    "        print(\"\\n===== DICE ROLLING GAME =====\")\n",
    "\n",
    "        input(\"Press Enter to roll the dice...\")\n",
    "\n",
    "        player_dice = random.randint(1, 6)\n",
    "        computer_dice = random.randint(1, 6)\n",
    "\n",
    "        print(\"You rolled:\", player_dice)\n",
    "        print(\"Computer rolled:\", computer_dice)\n",
    "\n",
    "        if player_dice > computer_dice:\n",
    "            print(\"You win!\")\n",
    "            self.player_score += 1\n",
    "\n",
    "        elif player_dice < computer_dice:\n",
    "            print(\"Computer wins!\")\n",
    "            self.computer_score += 1\n",
    "\n",
    "        else:\n",
    "            print(\"It's a tie!\")\n",
    "\n",
    "\n",
    "    # ---------------------------------\n",
    "    # 4. Coin Toss Game\n",
    "    # ---------------------------------\n",
    "    def coin_toss(self):\n",
    "\n",
    "        print(\"\\n===== COIN TOSS GAME =====\")\n",
    "\n",
    "        choice = input(\"Choose Heads or Tails: \").lower()\n",
    "\n",
    "        if choice not in [\"heads\", \"tails\"]:\n",
    "            print(\"Invalid choice!\")\n",
    "            return\n",
    "\n",
    "        result = random.choice([\"heads\", \"tails\"])\n",
    "\n",
    "        print(\"Coin result:\", result)\n",
    "\n",
    "        if choice == result:\n",
    "            print(\"You win!\")\n",
    "            self.player_score += 1\n",
    "\n",
    "        else:\n",
    "            print(\"Computer wins!\")\n",
    "            self.computer_score += 1\n",
    "\n",
    "\n",
    "    # ---------------------------------\n",
    "    # 5. Mini Cricket Game\n",
    "    # ---------------------------------\n",
    "    def mini_cricket(self):\n",
    "\n",
    "        print(\"\\n===== MINI CRICKET GAME =====\")\n",
    "\n",
    "        print(\"You have 3 balls.\")\n",
    "        print(\"Choose runs between 1 and 6.\")\n",
    "\n",
    "        player_runs = 0\n",
    "\n",
    "        for ball in range(1, 4):\n",
    "\n",
    "            try:\n",
    "                player = int(input(f\"Ball {ball} - Enter your runs (1-6): \"))\n",
    "\n",
    "                if player < 1 or player > 6:\n",
    "                    print(\"Please enter a number between 1 and 6.\")\n",
    "                    continue\n",
    "\n",
    "                computer = random.randint(1, 6)\n",
    "\n",
    "                print(\"Computer bowled:\", computer)\n",
    "\n",
    "                if player == computer:\n",
    "                    print(\"OUT!\")\n",
    "                    break\n",
    "\n",
    "                player_runs += player\n",
    "                print(\"Runs scored:\", player)\n",
    "\n",
    "            except ValueError:\n",
    "                print(\"Invalid input!\")\n",
    "\n",
    "        print(\"Your total score:\", player_runs)\n",
    "\n",
    "        computer_runs = random.randint(1, 15)\n",
    "\n",
    "        print(\"Computer score:\", computer_runs)\n",
    "\n",
    "        if player_runs > computer_runs:\n",
    "            print(\"You win!\")\n",
    "            self.player_score += 1\n",
    "\n",
    "        elif player_runs < computer_runs:\n",
    "            print(\"Computer wins!\")\n",
    "            self.computer_score += 1\n",
    "\n",
    "        else:\n",
    "            print(\"Match tied!\")\n",
    "\n",
    "\n",
    "    # ---------------------------------\n",
    "    # 6. Penalty Shootout\n",
    "    # ---------------------------------\n",
    "    def penalty_shootout(self):\n",
    "\n",
    "        print(\"\\n===== PENALTY SHOOTOUT =====\")\n",
    "\n",
    "        player_score = 0\n",
    "        computer_score = 0\n",
    "\n",
    "        for round_no in range(1, 4):\n",
    "\n",
    "            print(\"\\nRound\", round_no)\n",
    "\n",
    "            direction = input(\n",
    "                \"Choose left, center, or right: \"\n",
    "            ).lower()\n",
    "\n",
    "            if direction not in [\"left\", \"center\", \"right\"]:\n",
    "                print(\"Invalid direction!\")\n",
    "                continue\n",
    "\n",
    "            goalkeeper = random.choice(\n",
    "                [\"left\", \"center\", \"right\"]\n",
    "            )\n",
    "\n",
    "            print(\"Goalkeeper chose:\", goalkeeper)\n",
    "\n",
    "            if direction == goalkeeper:\n",
    "                print(\"Saved!\")\n",
    "\n",
    "            else:\n",
    "                print(\"GOAL!\")\n",
    "                player_score += 1\n",
    "\n",
    "        computer_score = random.randint(0, 3)\n",
    "\n",
    "        print(\"\\nYour goals:\", player_score)\n",
    "        print(\"Computer goals:\", computer_score)\n",
    "\n",
    "        if player_score > computer_score:\n",
    "            print(\"You win!\")\n",
    "            self.player_score += 1\n",
    "\n",
    "        elif player_score < computer_score:\n",
    "            print(\"Computer wins!\")\n",
    "            self.computer_score += 1\n",
    "\n",
    "        else:\n",
    "            print(\"It's a draw!\")\n",
    "\n",
    "\n",
    "    # ---------------------------------\n",
    "    # 7. Python Quiz\n",
    "    # ---------------------------------\n",
    "    def python_quiz(self):\n",
    "\n",
    "        print(\"\\n===== PYTHON QUIZ =====\")\n",
    "\n",
    "        questions = [\n",
    "            {\n",
    "                \"question\": \"Which keyword is used to define a function?\",\n",
    "                \"options\": [\"A. function\", \"B. def\", \"C. fun\", \"D. define\"],\n",
    "                \"answer\": \"b\"\n",
    "            },\n",
    "\n",
    "            {\n",
    "                \"question\": \"Which symbol is used for comments in Python?\",\n",
    "                \"options\": [\"A. //\", \"B. /*\", \"C. #\", \"D. --\"],\n",
    "                \"answer\": \"c\"\n",
    "            },\n",
    "\n",
    "            {\n",
    "                \"question\": \"Which function is used to display output?\",\n",
    "                \"options\": [\"A. display()\", \"B. print()\", \"C. show()\", \"D. output()\"],\n",
    "                \"answer\": \"b\"\n",
    "            },\n",
    "\n",
    "            {\n",
    "                \"question\": \"Which data type stores True or False?\",\n",
    "                \"options\": [\"A. int\", \"B. string\", \"C. bool\", \"D. float\"],\n",
    "                \"answer\": \"c\"\n",
    "            },\n",
    "\n",
    "            {\n",
    "                \"question\": \"Which function is used to get input from the user?\",\n",
    "                \"options\": [\"A. input()\", \"B. get()\", \"C. read()\", \"D. scan()\"],\n",
    "                \"answer\": \"a\"\n",
    "            }\n",
    "        ]\n",
    "\n",
    "        score = 0\n",
    "\n",
    "        for question in questions:\n",
    "\n",
    "            print(\"\\n\" + question[\"question\"])\n",
    "\n",
    "            for option in question[\"options\"]:\n",
    "                print(option)\n",
    "\n",
    "            answer = input(\"Enter your answer: \").lower()\n",
    "\n",
    "            if answer == question[\"answer\"]:\n",
    "                print(\"Correct!\")\n",
    "                score += 1\n",
    "\n",
    "            else:\n",
    "                print(\"Wrong!\")\n",
    "\n",
    "        print(\"\\nQuiz completed!\")\n",
    "        print(\"Your score:\", score, \"/\", len(questions))\n",
    "\n",
    "        if score >= 3:\n",
    "            print(\"Good job!\")\n",
    "            self.player_score += 1\n",
    "        else:\n",
    "            print(\"Keep practicing!\")\n",
    "\n",
    "\n",
    "    # ---------------------------------\n",
    "    # Main Menu\n",
    "    # ---------------------------------\n",
    "    def main_menu(self):\n",
    "\n",
    "        while True:\n",
    "\n",
    "            print(\"\\n================================\")\n",
    "            print(\"       MINI GAMES HUB\")\n",
    "            print(\"================================\")\n",
    "\n",
    "            print(\"1. Rock Paper Scissors\")\n",
    "            print(\"2. Number Guessing Game\")\n",
    "            print(\"3. Dice Rolling Game\")\n",
    "            print(\"4. Coin Toss Game\")\n",
    "            print(\"5. Mini Cricket Game\")\n",
    "            print(\"6. Penalty Shootout\")\n",
    "            print(\"7. Python Quiz\")\n",
    "            print(\"8. Show Score\")\n",
    "            print(\"9. Exit\")\n",
    "\n",
    "            print(\"================================\")\n",
    "\n",
    "            choice = input(\"Enter your choice (1-9): \")\n",
    "\n",
    "            if choice == \"1\":\n",
    "                self.rock_paper_scissors()\n",
    "\n",
    "            elif choice == \"2\":\n",
    "                self.number_guessing()\n",
    "\n",
    "            elif choice == \"3\":\n",
    "                self.dice_rolling()\n",
    "\n",
    "            elif choice == \"4\":\n",
    "                self.coin_toss()\n",
    "\n",
    "            elif choice == \"5\":\n",
    "                self.mini_cricket()\n",
    "\n",
    "            elif choice == \"6\":\n",
    "                self.penalty_shootout()\n",
    "\n",
    "            elif choice == \"7\":\n",
    "                self.python_quiz()\n",
    "\n",
    "            elif choice == \"8\":\n",
    "                print(\"\\n===== SCORE =====\")\n",
    "                print(\"Player Score:\", self.player_score)\n",
    "                print(\"Computer Score:\", self.computer_score)\n",
    "\n",
    "            elif choice == \"9\":\n",
    "                print(\"\\nThank you for playing Mini Games Hub!\")\n",
    "                print(\"Exiting application...\")\n",
    "                break\n",
    "\n",
    "            else:\n",
    "                print(\"Invalid choice! Please select 1-9.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "acbfa520-dab2-4509-b49a-0974f3249c15",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "================================\n",
      "       MINI GAMES HUB\n",
      "================================\n",
      "1. Rock Paper Scissors\n",
      "2. Number Guessing Game\n",
      "3. Dice Rolling Game\n",
      "4. Coin Toss Game\n",
      "5. Mini Cricket Game\n",
      "6. Penalty Shootout\n",
      "7. Python Quiz\n",
      "8. Show Score\n",
      "9. Exit\n",
      "================================\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter your choice (1-9):  7\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "===== PYTHON QUIZ =====\n",
      "\n",
      "Which keyword is used to define a function?\n",
      "A. function\n",
      "B. def\n",
      "C. fun\n",
      "D. define\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter your answer:  b\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Correct!\n",
      "\n",
      "Which symbol is used for comments in Python?\n",
      "A. //\n",
      "B. /*\n",
      "C. #\n",
      "D. --\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter your answer:  c\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Correct!\n",
      "\n",
      "Which function is used to display output?\n",
      "A. display()\n",
      "B. print()\n",
      "C. show()\n",
      "D. output()\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter your answer:  b\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Correct!\n",
      "\n",
      "Which data type stores True or False?\n",
      "A. int\n",
      "B. string\n",
      "C. bool\n",
      "D. float\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter your answer:  c\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Correct!\n",
      "\n",
      "Which function is used to get input from the user?\n",
      "A. input()\n",
      "B. get()\n",
      "C. read()\n",
      "D. scan()\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter your answer:  a\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Correct!\n",
      "\n",
      "Quiz completed!\n",
      "Your score: 5 / 5\n",
      "Good job!\n",
      "\n",
      "================================\n",
      "       MINI GAMES HUB\n",
      "================================\n",
      "1. Rock Paper Scissors\n",
      "2. Number Guessing Game\n",
      "3. Dice Rolling Game\n",
      "4. Coin Toss Game\n",
      "5. Mini Cricket Game\n",
      "6. Penalty Shootout\n",
      "7. Python Quiz\n",
      "8. Show Score\n",
      "9. Exit\n",
      "================================\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter your choice (1-9):  10\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Invalid choice! Please select 1-9.\n",
      "\n",
      "================================\n",
      "       MINI GAMES HUB\n",
      "================================\n",
      "1. Rock Paper Scissors\n",
      "2. Number Guessing Game\n",
      "3. Dice Rolling Game\n",
      "4. Coin Toss Game\n",
      "5. Mini Cricket Game\n",
      "6. Penalty Shootout\n",
      "7. Python Quiz\n",
      "8. Show Score\n",
      "9. Exit\n",
      "================================\n"
     ]
    }
   ],
   "source": [
    "game_hub = MiniGamesHub()\n",
    "game_hub.main_menu()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "09e64cc0-4c98-4d8a-a989-b023cda05a80",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
